### ISSUE TITLE
[19/02/07]目黒Deもくもく会 [takahashi19]

### ISSUE THREAD

**Issue by takahashi19** [keitabox128/mokumoku#10]
## ネーム
takahashi

## やっていること、勉強していること
・Rails

## 今日もくもくすること
・GitHubログインの設置

## 最近の課題
・GitHubログイン
・AWSが快適すぎて近くに欲しい

**Comment by takahashi19** [comment]
・GitHubログインは出来なかった。。
・3月1日LT大会の主催企画の連絡等は進んだ

**Comment by keitabox128** [comment]
課題は次から次へとありますが、頑張りましょう。LT発表会何かできればと思います。
