### ISSUE TITLE
[19/02/07] 目黒Deもくもく会 [tsu-nera]

### ISSUE THREAD

**Issue by tsu-nera** [keitabox128/mokumoku#12]
## ネーム

tsu-nera

## やっていること、勉強していること

Rails, Nuxt.js, AWS。

就活のためのポートフォリオを作成しています。
チーム開発で2つサービスをつくっています。

## 今日もくもくすること

Webスクレイピングのロジック改善

## 最近の課題

インフラ周りをAWSで構築しようか悩んでいる。

**Comment by tsu-nera** [comment]
本日はスクレイピングのページネーション対応を行いました。
3サイト中1サイトだけ対応できました。

**Comment by keitabox128** [comment]
躓きながらも進む姿勢が素晴らしいです。一緒に頑張りましょう
