### ISSUE TITLE
[19/02/07]目黒Deもくもく会 [tatsuya413]

### ISSUE THREAD

**Issue by yk-port** [keitabox128/mokumoku#13]
## ネーム
tatsuya

## やっていること、勉強していること
- Rails
- React.js

## 今日もくもくすること
1. 書籍を進めるだけ進める
 - 現場で使える Ruby on Rails 5速習実践ガイド

## 最近の課題
- 全然コードを書いていない…

**Comment by yk-port** [comment]
### できたこと
- 101ページまで進めた（超基本的なCRUD処理の復習になった）
- ちまちまコミットしたので、多少githubに草生えた

### 次回の目標
1. 本日中にChapter3を終わらす
2. 今週末までにChapter4を終わらす

### 個人的な目標
- 5月くらいまでに開発の現場に転職したいな〜…

**Comment by keitabox128** [comment]
コード書く習慣付けないとほんとに他のことに時間を割いてしまいがちです（真顔
