### ISSUE TITLE
[19/02/07]目黒Deもくもく会 [mizuki]

### ISSUE THREAD

**Issue by MizRubyprogrammer** [keitabox128/mokumoku#14]
## ネーム
みずき
## やっていること、勉強していること
Ruby
## 今日もくもくすること
プロを目指す人のためのRuby
## 最近の課題
Rubyの基礎力

**Comment by MizRubyprogrammer** [comment]
プロを目指す人のためのRuby 2章の途中まで終わりました。
ヒアドキュメントの書き方、論理演算子の扱い方、後置if、三項演算子、丸め誤差を防ぐRationalクラス、フォーマット指定のsprintfメソッド、Numericクラスの概要等を学びました。

**Comment by keitabox128** [comment]
基礎力って意外と必要なんですよね。基礎体力とか。
