### ISSUE TITLE
[2019/02/07] 目黒Deもくもく会[kazuho]

### ISSUE THREAD

**Issue by kazuho01** [keitabox128/mokumoku#15]
## ネーム
かずほ

## やっていること、勉強していること
テックアカデミー

## 今日もくもくすること
テックアカデミーの課題

## 最近の課題
まだまだ理解が浅い…

**Comment by kazuho01** [comment]
お気に入り機能の課題を進めていました。
できておりません…涙

**Comment by keitabox128** [comment]
初心者にとってチュートリアルですら難しく感じてしまいますよね。
