### ISSUE TITLE
Issue: [2019/02/07] 目黒Deもくもく会 [YUUKI]

### ISSUE THREAD

**Issue by YuukiTetsuya** [keitabox128/mokumoku#16]
## ネーム
YUUKI
## やっていること、勉強していること
Ruby on Rails チュートリアル
就活(今日から)
ポートフォリオ2作目制作
## 今日もくもくすること
Ruby on Rails チュートリアル
## 最近の課題
就活の進め方

**Comment by YuukiTetsuya** [comment]
Railsチュートリアル 14.2.2 統計と[Follow]フォームを終わらせた。
具体的には、Twitterで言う「ログインしてる状態でのタイムライン」に

フォローしてる人の投稿→フォロー解除ボタンを表示
フォローしてない人の投稿→フォローボタンを表示

このような条件式を使って実装した。

**Comment by YuukiTetsuya** [comment]
フォローしてる人の投稿→フォロー解除ボタンを表示

![スクリーンショット 2019-02-07 17.05.39.png](https://qiita-image-store.s3.amazonaws.com/0/244639/8c97ed5a-9660-8108-982f-4af0cae5d69d.png)

フォローしてない人の投稿→フォローボタンを表示

![スクリーンショット 2019-02-07 15.56.13.png](https://qiita-image-store.s3.amazonaws.com/0/244639/3a7ca406-31c0-f8ce-c601-7f6b43ffd7fc.png)

**Comment by keitabox128** [comment]
就活相談とかもできるようになりたいですね
