### ISSUE TITLE
19/2/14 目黒Deもくもく会[tsu-nera]

### ISSUE THREAD

**Issue by tsu-nera** [keitabox128/mokumoku#17]
## ネーム

tsu-nera （原田）

## やっていること、勉強していること

* お仕事探しています。
* Rails, Nuxt.jsをつかって、自分を売り込むためのポートフォリオを作成しています。
* ２つのチームに所属してWebサービスをチーム開発しています。

## 今日もくもくすること

* 複数の外部サイトからスクレイピングで取得した情報をSlackに流し込む部分をつくる。

## 最近の課題

* Webサービスのグロースの仕方。つくって終わりは虚しい。

**Comment by tsu-nera** [comment]
https://github.com/peach-hack/auto-matching/pull/463

**Comment by keitabox128** [comment]
お疲れ様でした。就活頑張ってください。
