### ISSUE TITLE
 [19/02/14] 目黒Deもくもく会 [wawasawa]

### ISSUE THREAD

**Issue by wawasawa** [keitabox128/mokumoku#18]
## ネーム
wawasawa（齋藤）

## やっていること、勉強していること
英語学習ウェブアプリの開発

## 今日もくもくすること
ソートボタンの実装など

## 最近の課題
リリースのケツを決めなければ。。。

**Comment by wawasawa** [comment]
## 本日の成果
* リファクタリングが7割完了

**Comment by keitabox128** [comment]
リファクタリングできるってすごいですね。お疲れ様でした。
