### ISSUE TITLE
[19/02/14]目黒Deもくもく会[takahashi]

### ISSUE THREAD

**Issue by takahashi19** [keitabox128/mokumoku#19]
## ネーム
TH
Twitter：@TH03045840
## やっていること、勉強していること
・未経験（Railsの学習歴3ヶ月　Java6ヶ月）
・Rails
・デヴァイス/GitHubログイン
## 今日もくもくすること
・メール返す
・勉強会の場所を渋谷と新宿で候補探す
・ログイン画面の作成

## 最近の課題
・勉強会とかそういうのカフェ場所探し

## 最近の話題
・AWS要望の掲示板にリクエストを書いたら７票ほど入っていて嬉しかった
[![Screenshot from Gyazo](https://gyazo.com/f6656a7359a02a6ecc01e6a34b9da70f/raw)](https://gyazo.com/f6656a7359a02a6ecc01e6a34b9da70f)

**Comment by takahashi19** [comment]
## 成果発表
・メール返す→完了
・場所探し→微妙。見つかってないので模索中
　https://github.com/WEBsinjyuku/github-open-products/issues/109
・GitHubログイン→希望が見えた・・

告知
・LT大会よければ来てください
　https://ossteam.connpass.com/event/119983/
・チーム開発やりたい人でフロント側
　SEO/アナリティクス/デザイン/フロントエンドに興味ある人（ノースキルOKです）
・

**Comment by keitabox128** [comment]
LT大会に向けて頑張って下さい
