### ISSUE TITLE
[19/02/14]目黒Deもくもく会[ray]

### ISSUE THREAD

**Issue by ray9210** [keitabox128/mokumoku#20]
## ネーム
ray  (moriya)

## やっていること、勉強していること
新卒時はソフトウェア開発者(Android)でしたがその後Project managerに移ってからはコーディングはほぼしていません。
現在起業中でリソース不足から自分でも開発をできるようになりたいと思い来ました。

## 今日もくもくすること
まずは、iOS/Androidのbuild環境を整えて、簡単なbugは自分で解決できるようなりたい。

## 最近の課題
こんなの作ってます
https://www.fiika.jp/

**Comment by ray9210** [comment]
**本日の成果**
元同僚２人に見つかったのでサービスの宣伝をしておいた。
昨日インターナルリリースされたアプリのテストを行った。
Androidの開発環境を整え、実機デバッグができるようになった。

もくもく会は集中できますね〜。また来たいです。

**Comment by keitabox128** [comment]
お疲れ様でした。
