### ISSUE TITLE
[19/02/14] 目黒Deもくもく会 [wadadones]

### ISSUE THREAD

**Issue by wadadones** [keitabox128/mokumoku#21]
## ネーム
わだどんです。わだ or どんで呼ばれることが多いです。

## やっていること、勉強していること
情報系の大学院生です。
Railsでサークル業務効率化アプリケーションを作っています。最近はJavaScript(jQuery)をいじり始めて、アプリに適用しているところです。
PHPもそのうちいじりたいと思ってて興味が発散してます。

## 今日もくもくすること
indexのデザイン調整&モーダル必要そうならつけたい

## 最近の課題
gitをわかっているようで実際に活用できてない
HTML/CSSのリファクタリングをうまくやりたい

**Comment by wadadones** [comment]
## 成果
- 日付に合わせてコンテンツの色を変えた(jQuery)
- 一つの要素をgridで分割、アイテムをうまく散りばめた(HTML/CSS)
- クリックイベントを一部実装、モーダル実装までは行ってない
- null制約がかかってたカラムをマイグレーションでnull許容

**Comment by keitabox128** [comment]
お疲れ様でした。
