### ISSUE TITLE
[19/02/22] 目黒Deもくもく会 [th]

### ISSUE THREAD

**Issue by takahashi19** [keitabox128/mokumoku#23]
## ネーム
takahashi
## やっていること、勉強していること
Railsの勉強（実装）

## 今日もくもくすること
・プレゼン資料の作成
・各種連絡
## 最近の課題
・

**Comment by takahashi19** [comment]
## 成果
・プレゼン資料の作成（構想のみ）
・チーム開発の打ち合わせ

**Comment by keitabox128** [comment]
お疲れ様でした。
