### ISSUE TITLE
[19/02/22] 目黒Deもくもく会 [saito]

### ISSUE THREAD

**Issue by wawasawa** [keitabox128/mokumoku#26]
## ネーム
saito

## やっていること、勉強していること
英語学習アプリの開発

## 今日もくもくすること
はじめてのフリー案件のための環境構築

**Comment by wawasawa** [comment]
## 成果
・MySQLのインストール、初期設定まで終わった。

**Comment by keitabox128** [comment]
お疲れ様でした。
