### ISSUE TITLE
[19/02/22] 目黒もくもく会[tsu-nera]

### ISSUE THREAD

**Issue by tsu-nera** [keitabox128/mokumoku#27]
## ネーム

tsu-nera(原田)

## やっていること、勉強していること

- 就活
- webサービス開発（ポートフォリオサイト）

## 今日もくもくすること

- webサービスのバグ改修

## 最近の課題

仕事ほしい

**Comment by tsu-nera** [comment]
## 今日の成果

* 和田さんという経営者を招いて、AWS Loftで事業紹介をしてもらいました。

https://aki-katsu.co.jp/

* 今開発しているサービスがどこかバグっているため、調べています。

https://github.com/WEBsinjyuku/meister-hackers/pull/147

**Comment by keitabox128** [comment]
お疲れ様でした。
