### ISSUE TITLE
[19/03/04] 目黒Deもくもく会[tsu-nera]

### ISSUE THREAD

**Issue by tsu-nera** [keitabox128/mokumoku#30]
## ネーム

tsu-nera(原田）

## やっていること、勉強していること

* DIVE INTO CODEのDEMODAYで優勝するために、Webサービスをチーム開発しています。
* https://diveintocode.jp/demoday
* 無職なので、仕事を探しています。

## 今日もくもくすること

* DIC DEMODAYに向けたWebサービスのビジネス戦略の策定。
* Dsiciplined Entrepreneurship workbookを読みます。(MITの起業の教科書)
* https://amzn.to/2NF7I14

## 最近の課題

マネタイズ、とは？

**Comment by tsu-nera** [comment]
https://github.com/WEBsinjyuku/meister-hackers/issues/276#issuecomment-469104899

**Comment by tsu-nera** [comment]
## 本日の成果

DISCIPLINED ENTREPRENERURSHIP の 24ステップの２つまで進みました。

* 市場セグメント分析をしました。
* 足がかり市場を決定しました。
* マネタイズのビジネスモデルを決めました。
* エンドユーザ、とくにペルソナ設定をしました。

**Comment by keitabox128** [comment]
お疲れ様でした。
