### ISSUE TITLE
[19/03/04] 目黒Deもくもく会 [TH]

### ISSUE THREAD

**Issue by takahashi19** [keitabox128/mokumoku#31]
## ネーム
takahashi
## やっていること、勉強していること
・Rails
・チーム開発のタスク

## 今日もくもくすること
・タスク振り
・ビジネスサイド調整
・デザイン構築

## 最近の話題
・就活！！のなかでなぜみんな自社会社入社をアピールしたがるのか

**Comment by takahashi19** [comment]
## 成果
・タスクの整理
・就活の面談

**Comment by keitabox128** [comment]
お疲れ様でした。
