### ISSUE TITLE
 [19/03/04] 目黒Deもくもく会 [k.oishi]

### ISSUE THREAD

**Issue by k-oishi** [keitabox128/mokumoku#32]
## ネーム
k.oishi（大石 和明）

## やっていること、勉強していること
・中小零細企業向けのホームページ制作
・デザイン
・外国人向け飲食店紹介アプリの開発（スタートアップ）

## 今日もくもくすること
PHP, Wordpress 顧客向けHPの作成。時間帯別メッセージ表示機能の作成

## 最近の課題
・外国人向け飲食店紹介アプリの開発（スタートアップ）
上記プロジェクトのメンバー探しをしております！

**Comment by k-oishi** [comment]
## 本日の成果
・新規ウェブサイト画面確認
・見積もり算出
・デザイナー指示

**Comment by yuumi3** [comment]
本日はプレゼンありがとうございます。
思い出せなかった大田区出身の出来る自民党議員は 平 将明 でした。
経済特区とか、IT化とかをやってますが石場派なので現在は冷遇されてるようです。
http://www.taira-m.jp

**Comment by k-oishi** [comment]
@yuumi3 
こちらこそありがとうございました！
そして、わざわざ調べていただきありがとうございます。
本日のLTの時間では企画のブラッシュアップ/意見収集の面で大いに役立ちました。
またご一緒にもくもくさせてください！

**Comment by keitabox128** [comment]
お疲れ様
