### ISSUE TITLE
目黒Deもくもく会3/11 [riku1027]

### ISSUE THREAD

**Issue by riku1027** [keitabox128/mokumoku#35]
## ネーム
髙橋陸

## やっていること、勉強していること
railsで宿題提出や生徒を管理するためのシステムを作っている
自作のアプリを作っていて、railsをちゃんと理解せずに使っている感じがしたため、rubyの基礎から学び直している
## 今日もくもくすること
udemy(sintra)、チェリー本(正規表現、例外処理)、自作のシステムを進める
## 最近の課題
これまでなんとなくrailsを動かしてきたので応用的なことができない

**Comment by keitabox128** [comment]
今日はありがとうございました！twitterとかもやっているのでconnpassで探して頂ければ！

**Comment by riku1027** [comment]
こちらこそありがとうございました！参加出来て良かったです^_^
探してみます！
