### ISSUE TITLE
[19/03/25] 目黒Deもくもく会[tsu-nera]

### ISSUE THREAD

**Issue by tsu-nera** [keitabox128/mokumoku#38]
## ネーム

tsu-nera(原田)

## やっていること、勉強していること

* 無職で就活中。
* チーム開発を２つやっています。

https://github.com/WEBsinjyuku/meister-hackers
https://github.com/peach-hack/titan

## 今日もくもくすること

* WEBサービス立ち上げのためのユーザインタビューをしたので、インタビュー結果をまとめ。
* DIC DEMODAYのプレゼン資料

## 最近の課題

* 健康ですかね。

**Comment by tsu-nera** [comment]
## 本日の成果

### Meister Hakers - DEMODAYプレゼン下書き

https://docs.google.com/presentation/d/1UIiwIj0QDnvn1g8ztS57c0FAbWM3hiD-yGbTrExd8tQ/edit?usp=sharing

### Titan - 要件整理

discourseという掲示板を利用しています（けっこう使いやすい）

http://forum-titan-development-6349.nodechef.com/

MITの起業理論に従っています。

https://amzn.to/2FxsNrM

Twitterマーケティングについての調査

**Comment by keitabox128** [comment]
お疲れさまでした。
