### ISSUE TITLE
 [19/01/31] 目黒Deもくもく会 tsu-nera

### ISSUE THREAD

**Issue by tsu-nera** [keitabox128/mokumoku#7]
## ネーム

tsu-nera

## どんなことしているか、仕事等

趣味でWebサービスを開発しながら職を探しています。

## 勉強している言語

Ruby on Rails, Nuxt.js

## 今日もくもくすること

BILL AULETの著作を読んでスタートアップの方法を模索する。

- [Amazon \| Disciplined Entrepreneurship Workbook \(English Edition\) \[Kindle edition\] by Bill Aulet \| Small Business & Entrepreneurship \| Kindleストア](https://www.amazon.co.jp/Disciplined-Entrepreneurship-Workbook-English-Aulet-ebook/dp/B06XS5H98Q/ref=pd_sim_0_1/358-2943086-7383850?_encoding=UTF8&pd_rd_i=B06XS5H98Q&pd_rd_r=02ce473b-2513-11e9-a395-81b790b7098e&pd_rd_w=9flY8&pd_rd_wg=HRCGZ&pf_rd_p=68cfebef-f8b4-4691-9d72-a10f0956615a&pf_rd_r=0Q7PZ8ECYHW3D6N40NCA&psc=1&refRID=0Q7PZ8ECYHW3D6N40NCA)

- [ビジネス・クリエーション！ \| Bill Aulet, 月沢 李歌子 \| ビジネス・経済 \| Kindleストア \| Amazon](https://www.amazon.co.jp/%E3%83%93%E3%82%B8%E3%83%8D%E3%82%B9%E3%83%BB%E3%82%AF%E3%83%AA%E3%82%A8%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%EF%BC%81-Bill-Aulet-ebook/dp/B00RUPCU42/ref=pd_sim_0_2/358-2943086-7383850?_encoding=UTF8&pd_rd_i=B00RUPCU42&pd_rd_r=02ce473b-2513-11e9-a395-81b790b7098e&pd_rd_w=9flY8&pd_rd_wg=HRCGZ&pf_rd_p=68cfebef-f8b4-4691-9d72-a10f0956615a&pf_rd_r=0Q7PZ8ECYHW3D6N40NCA&psc=1&refRID=0Q7PZ8ECYHW3D6N40NCA)

## 今感じている技術的な課題

Webサービスをなにも考えずにつくっても誰も利用しないゴミができるのだけなので、戦略的に構築しなければならない。

**Comment by keitabox128** [comment]
確認しました。
